#!/usr/bin/env Rscript
# =============================================================================
# 13_backfill_pipeline_sample_id.R
#
# The curated tables ship a `pipeline_sample_id` column and it is empty in all 13.
# That emptiness is why the join has to be DERIVED on every run, and a derived
# join is what produced several of this re-run's defects (a regex matching the
# curated id instead of the pipeline id; a frozen side-car reinstating the v1
# roster). Filling the column once ends that.
#
# WRITES PASTE-READY FILES, NOT THE CURATION ITSELF. Each curated dataset exists
# as a .csv/.xlsx pair regenerated by its own build_meta_*.py; writing into
# /LARGE1 directly would desynchronise the pair and be overwritten by the next
# build. Output here is one file per dataset, IN CURATED ROW ORDER, so the
# pipeline_sample_id column can be pasted straight in.
#
# Input : 01_preprocess/00_curated_join_map.tsv   (from 00_curated_manifest.R)
# Output: 00_project/metadata/backfill/<dataset>__pipeline_sample_id.tsv
#         00_project/metadata/backfill/ALL__pipeline_sample_id.tsv
#
# Usage: Rscript scripts/99_admin/13_backfill_pipeline_sample_id.R
# =============================================================================

suppressPackageStartupMessages({library(data.table); library(readxl); library(here)})
source(here::here("scripts", "config", "config_paths.R"))
source(here::here("scripts", "config", "config_qc.R"))
source(here::here("scripts", "config", "utils.R"))

CURATED_DIR <- "/LARGE1/gr10634/gaozy/aml_niche_net/00_raw/metadata"
OUT_DIR     <- file.path(PROJECT_ROOT, "00_project", "metadata", "backfill")
dir.create(OUT_DIR, showWarnings = FALSE, recursive = TRUE)

J <- fread(file.path(DIR_PREPROCESS, "00_curated_join_map.tsv"), colClasses = "character")
message("[1] join map: ", nrow(J), " curated rows")

load_meta <- function(d) {
  p   <- file.path(CURATED_DIR, d)
  csv <- list.files(p, "^meta_.*\\.csv$", full.names = TRUE)
  if (length(csv)) return(fread(csv[1], colClasses = "character"))
  xls <- list.files(p, "^meta_.*\\.xlsx$", full.names = TRUE)[1]
  sh  <- grep("^meta_", readxl::excel_sheets(xls), value = TRUE)[1]
  as.data.table(readxl::read_excel(xls, sheet = sh, col_types = "text"))
}
dirs <- setdiff(list.dirs(CURATED_DIR, recursive = FALSE, full.names = FALSE), "BoneMarrowMap")

all_out <- list()
for (d in dirs) {
  ds <- gsub(" ", "", d)
  cu <- load_meta(d)
  jj <- J[dataset == ds]
  # Join on sample_id and keep the CURATED row order, so the result is a column
  # that lines up with the file it is going back into.
  m <- merge(data.table(row = seq_len(nrow(cu)), sample_id = cu$sample_id),
             jj[, .(sample_id, pipeline_sample_id, join_rule)],
             by = "sample_id", all.x = TRUE, sort = FALSE)
  setorder(m, row)
  stopifnot(nrow(m) == nrow(cu), identical(m$sample_id, cu$sample_id))

  n_fill <- sum(!is.na(m$pipeline_sample_id) & nzchar(m$pipeline_sample_id))
  n_multi <- sum(grepl(";", m$pipeline_sample_id))
  message(sprintf("    %-14s %3d rows | %3d filled | %2d map to >1 pipeline sample | %d unresolved",
                  ds, nrow(m), n_fill, n_multi, sum(is.na(m$pipeline_sample_id))))

  # BROADCAST IS NOT A MAPPING AND MUST NOT BE PASTED AS ONE. It fires when every
  # curated row in a dataset is identical across all pipeline-relevant fields, so
  # a per-sample join carries no information -- GSE239721, whose GSM<->PT map is
  # private but whose 20 rows agree on every field the pipeline reads. Writing all
  # 20 pipeline ids into each of the 20 rows would assert 20 one-to-many links
  # that do not exist. The honest cell is empty, with the reason beside it.
  m[join_rule == "broadcast", pipeline_sample_id := NA_character_]
  m[join_rule == "broadcast",
    join_rule := "broadcast (per-sample identity not recoverable; dataset is homogeneous so it is immaterial)"]

  out <- m[, .(sample_id, pipeline_sample_id, join_rule)]
  fwrite_safe(out, file.path(OUT_DIR, paste0(ds, "__pipeline_sample_id.tsv")), sep = "\t")
  all_out[[ds]] <- cbind(dataset = ds, out)
}

A <- rbindlist(all_out)
fwrite_safe(A, file.path(OUT_DIR, "ALL__pipeline_sample_id.tsv"), sep = "\t")

message("\n[2] join rules behind the filled values:")
print(A[, .N, by = join_rule][order(-N)])

# A value with a ';' means one curated row legitimately covers several pipeline
# samples (a donor split across libraries, or a homogeneous-dataset broadcast).
# Flagged because pasting it into a single cell is correct but easy to misread as
# a formatting error.
multi <- A[grepl(";", pipeline_sample_id)]
if (nrow(multi)) {
  message("\n    ", nrow(multi), " curated row(s) map to MORE THAN ONE pipeline sample.",
          " The ';'-separated value is correct, not a formatting artefact:")
  print(multi[, .(dataset, sample_id, n = lengths(strsplit(pipeline_sample_id, ";")), join_rule)][
        , .N, by = .(dataset, join_rule, n)][order(dataset)])
}

message("\n[done] ", OUT_DIR)
message("  paste the pipeline_sample_id column into each meta_<dataset>_v2.*; row order matches.")
